[platformio]
default_envs =
  xiao_esp32s3
  xiao_esp32c3
  xiao_esp32c5
  xiao_esp32c6

[env]
framework = arduino
monitor_speed = 115200

build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=0
  -DCHAINOSCPAD_PLATFORMIO

lib_deps =
  hideakitai/ArduinoOSC@0.6.0
  bblanchon/ArduinoJson@^7.4.2

monitor_filters =
  esp32_exception_decoder
  time

[env:xiao_esp32s3]
platform = espressif32@6.9.0
board = seeed_xiao_esp32s3
build_flags =
  ${env.build_flags}
  -DCHAINOSCPAD_BOARD_XIAO_ESP32S3

[env:xiao_esp32c3]
platform = espressif32@6.9.0
board = seeed_xiao_esp32c3
build_flags =
  ${env.build_flags}
  -DCHAINOSCPAD_BOARD_XIAO_ESP32C3

[env:xiao_esp32c5]
platform = https://github.com/Seeed-Studio/platform-seeedboards/archive/85c1da71176e03af4b87561032274a81449a873c.zip
board = seeed-xiao-esp32-c5
extra_scripts = pre:scripts/platformio_seeed_esp.py
platform_packages =
  framework-arduinoespressif32@https://github.com/espressif/arduino-esp32/releases/download/3.3.7/esp32-core-3.3.7.tar.xz
  framework-arduinoespressif32-libs@https://github.com/espressif/arduino-esp32/releases/download/3.3.7/esp32-core-3.3.7-libs.tar.xz
  toolchain-riscv32-esp@https://github.com/pioarduino/registry/releases/download/0.0.1/riscv32-esp-elf-14.2.0_20251107.zip
  tool-esptoolpy@https://github.com/pioarduino/registry/releases/download/0.0.1/esptoolpy-v5.1.2.zip
build_flags =
  ${env.build_flags}
  -DCHAINOSCPAD_BOARD_XIAO_ESP32C5

[env:xiao_esp32c6]
platform = https://github.com/Seeed-Studio/platform-seeedboards/archive/6e8494feaec5fa45882e8cf2f33d1e3f25fa709f.zip
board = seeed-xiao-esp32-c6
build_flags =
  ${env.build_flags}
  -DCHAINOSCPAD_BOARD_XIAO_ESP32C6
