[platformio]
default_envs = xiao_esp32s3

[env:xiao_esp32s3]
platform = espressif32@6.9.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=0
  -DCHAINOSCPAD_PLATFORMIO

lib_deps =
  hideakitai/ArduinoOSC@0.6.0

monitor_filters =
  esp32_exception_decoder
  time
